### ISSUE TITLE
[EMAC] data finder

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#137]
Needs to be run before preprocessor (i.e. data finder module)

**Input**
* root path
* variable name(s) (CMOR); in case of derived CMOR variables names of all CMOR variables needed to calculate derived variable
* path + filename of mapping table (EMAC --> CMOR)

**Output**
* list of filename(s) containing required EMAC variable(s)

**Tasks**
- [x] update EMAC project class
- [x] read and parse new entries in config-developer.yml
- [x] find the input files for given root path and CMOR variable name; if CMOR variable is a derived variable, then all CMOR variables required to calculate the derived CMOR variable need to be considered
- [x] create mapping table (EMAC variable(s) --> CMOR variable(s)) including possibility to specify variable derivation script(s)

**Comment by schlunma** [comment]
Successfully tested with derived and non-derived variables on dummy data.
