### ISSUE TITLE
[EMAC] CMORize-light data

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#139]
Read and convert ("CMORize-light") EMAC data

**Input**
* filename(s) of file containing required EMAC variable(s)
* mapping table (EMAC variable(s) --> CMOR variable)

**Output**
* Iris cube containing CMORized-light EMAC data

**Tasks**
- [ ] add meta data (e.g. longitudes, latitudes, time, units, etc.)
- [] scripts for deriving CMOR variable from EMAC variable(s)
- [ ] custom CMOR tables for non-existing CMOR variables

**Comment by schlunma** [comment]
Run first successful tests with dummy data including:

- CMIP5 data for comparison (to check if something broke)
- Simple CMOR variable with only one entry in mapping table and no EMAC derive script
- Complex CMOR variable with two entries in mapping table (from different channels) and an EMAC derive script
- Derived CMOR variable consisting of the two CMOR variable mentioned above

Note: **All** CMOR checks were successful :tada:

**Comment by schlunma** [comment]
Tested the following variables:

- [ ] clivi: {xivi_ave: Amon}
- [ ] clt: {aclcov_ave: Amon} #recipe
- [ ] clwvi: {xlvi_ave: Amon, xivi_ave: Amon} #recipe
- [ ] co2mass: {MP_CO2_ave: tracer_pdef_gp}
- [ ] evspsbl: {evap_ave: Amon} #recipe
- [ ] hfss: {ahfs_ave: Amon}
- [ ] hfls: {ahfl_ave: Amon}
- [ ] lnox: {NOxcg_ave: lnox_PaR_T_gp, NOxic_ave: lnox_PaR_T_gp} #recipe
- [ ] pr: {aprl_ave: Amon, aprc_ave: Amon, aprs_ave: Amon} #recipe
- [ ] prc: {aprc_ave: Amon}
- [ ] prl: {aprl_ave: Amon} #not cmor 
- [ ] prsn: {aprs_ave: Amon}
- [ ] prw: {qvi_ave: Amon}
- [ ] siconca: {seaice_ave: Amon} (**CMOR table missing**)
- [ ] sithick: {siced_ave: Amon}
- [ ] rlds: {flxtbot_ave: Amon, tradsu_ave: Amon} #recipe
- [ ] rlus: {tradsu_ave: Amon}
- [ ] rlut: {flxttop_ave: Amon}
- [ ] rlutcs: {flxtftop_ave: Amon}
- [ ] rsds: {flxsbot_ave: Amon, sradsu_ave: Amon} #recipe
- [ ] rsdt: {flxstop_ave: Amon, srad0u_ave: Amon} #recipe
- [ ] rsus: {sradsu_ave: Amon}
- [ ] rsut: {srad0u_ave: Amon}
- [ ] rsutcs: {flxusftop_ave: Amon}
- [ ] rtmt: {flxttop_ave: Amon, flxstop_ave: Amon} #recipe
- [ ] tas: {temp2_ave: Amon}
- [ ] ts: {tsurf: Amon}
- [ ] tosga: {tosga_ave: Omon}
- [ ] toz: {toz: column}

- [ ] TN_GHG_CO2: {TN_GHG_CO2: import_grid}
- [ ] TN_GHG_N2O: {TN_GHG_N2O: import_grid}
- [ ] TN_GHG_CH4: {TN_GHG_CH4: import_grid}
- [ ] BB_CO_s: {BB_CO: import_grid} #recipe
- [ ] BB_N_s: {BB_N: import_grid} #recipe
- [ ] BB_SO_S: {BB_SO: import_grid} #recipe
- [ ] BB_AER_TC_s: {BB_AER_BC: import_grid, BB_AER_OC: import_grid} #recipe (add)
- [ ] ANTHNT_NO_s: {ANTHNT_NO: import_grid} #recipe
- [ ] ANTHNT_CO_s: {ANTHNT_CO: import_grid} #recipe
- [ ] ANTHNT_SO2_s: {ANTHNT_SO2: import_grid} #recipe
- [ ] ANTHNT_AER_TC_s: {ANTHNT_AER_BC: import_grid, ANTHNT_AER_OC: import_grid} #recipe (add)
- [ ] ROAD_NO: {ROAD_NO: import_grid}
- [ ] ROAD_AER_BC: {ROAD_AER_BC: import_grid}
- [ ] SHIP_NO_s: {SHIP_NO: import_grid} #recipe
- [ ] SHIP_SO2_S: {SHIP_SO2: import_grid} #recipe
- [ ] SHIP_AER_BC_s: {SHIP_AER_B: import_grid} #recipe
- [ ] AIRC_NO_s: {airc_NO: import_grid, aps: Amon, hyai: Amon, hybi: Amon} #recipe
- [ ] VOLC_SO2_s: {VOLC_SO2_SO2: import_grid, aps: Amon, hyai: Amon, hybi: Amon} #recipe

- [ ] MP_S: {MP_S_ave: tracer_pdef_gp}
- [ ] MP_CFCl3: {MP_CFCl3_ave: tracer_pdef_gp}
- [ ] MP_NH3: {MP_NH3_ave: tracer_pdef_gp}
- [ ] MP_N2O: {MP_N2O_ave: tracer_pdef_gp}
- [ ] MP_CO: {MP_CO_ave: tracer_pdef_gp}
- [ ] MP_CH4: {MP_CH4_ave: tracer_pdef_gp}
- [ ] MP_SO2: {MP_SO2_ave: tracer_pdef_gp}
- [ ] MP_OH: {MP_OH_ave: tracer_pdef_gp}
- [ ] MP_NO: {MP_NO_ave: tracer_pdef_gp}
- [ ] MP_NO2: {MP_NO2_ave: tracer_pdef_gp}
- [ ] MP_O3: {MP_O3_ave: tracer_pdef_gp}
- [ ] MP_CO2: {MP_CO2_ave: tracer_pdef_gp}
- [ ] MP_SO4mm_tot: {MP_SO4mm_ns_ave: tracer_pdef_gp, MP_SO4mm_ks_ave: tracer_pdef_gp, MP_SO4mm_as_ave: tracer_pdef_gp, MP_SO4mm_cs_ave: tracer_pdef_gp}  #calculate total SO4mm
- [ ] MP_SS_tot: {MP_SS_ks_ave: tracer_pdef_gp, MP_SS_as_ave: tracer_pdef_gp, MP_SS_cs_ave: tracer_pdef_gp}  #calculate total SS
- [ ] MP_BC_tot: {MP_BC_ks_ave: tracer_pdef_gp, MP_BC_as_ave: tracer_pdef_gp, MP_BC_cs_ave: tracer_pdef_gp, MP_BC_ki_ave: tracer_pdef_gp}  #calculate total BC
- [ ] MP_DU_tot: {MP_DU_as_ave: tracer_pdef_gp, MP_DU_cs_ave: tracer_pdef_gp, MP_DU_ai_ave: tracer_pdef_gp, MP_DU_ci_ave: tracer_pdef_gp}  #calculate total DU
- [ ] MP_ClOX: {MP_ClOX_ave: tracer_pdef_gp}
- [ ] MP_NOX: {MP_NOX_ave: tracer_pdef_gp}

**Comment by schlunma** [comment]
Remaining issues:

- [ ] (custom) CMOR table for `siconca` missing (only available in `obs4mips`

**Comment by schlunma** [comment]
ESMValTool can now read all of the desired variables :tada:
