### ISSUE TITLE
[EMAC] concatenation of preprocessor output

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#140]
Add capability of concatenating preprocessor output. At the moment, support for zonal means only.

**Input**
* path of output directory
* CMORized-light cube(s) containing EMAC data

**Output**
* flag: success/fail
* path + filename of concatenated file (as input for diagnostics): path(from user-config)/[dataset]_[short_name].nc

**Tasks**
- [x] check for existing file(s) for given simulation + variable
- [x] sort all data by time coordinate
- [x] write concatenated file(s)

**Comment by bjoernbroetz** [comment]
@LisaBock: Doing this in https://github.com/ESMValGroup/ESMValCore/tree/dev_append
