### ISSUE TITLE
[EMAC] infrastructure for monitoring

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#145]
Create infrastructure needed to use the ESMValTool as a monitoring tool for running model simulations.

**Tasks**
- [x] extend user-config.yml with quicklook entry including -> PR #154 
  * output_dir: quicklook output directory (concatenated netCDF files + plots)
  * recipe_dir: directory containing recipe template(s)
  * recipes: list of recipe(s) to be processed
- [x] create template recipe(s) to be used for monitoring (e.g. atmos_dynamics, atmos_chem, forcings)
- [x] create function to fill templates for given dataset (i.e. simulation) and time period
- [x] logging capability for all years of a simulation per recipe already processed
- [x] add possibility to run ESMValTool in quicklook mode -> PR #169 
  - get simulation name (via command line)
  - get years to be processed (via command line)
  - create one recipe from recipe templates and fill with given simulation(s) and years
- [ ] feature: check available years in input directory, compare to list of years already processed for given simulation and recipe and automatically "fill the gaps", i.e. process all missing years
- [ ] feature: ignore non-existing variables in quicklook recipes and continue with other variables (**bonus feature**)
