### ISSUE TITLE
Make preprocessor lazy

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#674]
Overview issue with laziness status of preprocessor functions:

- [ ] fix_file - copies files on disk
- [x] load
- [ ] derive - lazy for most variables #42, but all data is saved to disk #377
- [ ] fix_metadata - depends on model/variable
- [x] concatenate
- [x] cmor_check_metadata
- [x] extract_time
- [x] extract_season
- [x] extract_month
- [ ] fix_data - ?
- [ ] extract_levels - not if interpolation is needed #35
- [x] weighting_landsea_fraction
- [ ] mask_landsea - no
- [ ] mask_glaciated - no
- [ ] mask_landseaice - no
- [ ] regrid - no https://github.com/SciTools/iris/issues/3700
- [ ] extract_point - ?
- [ ] mask_fillvalues - no
- [ ] mask_above_threshold - no
- [ ] mask_below_threshold - no
- [ ] mask_inside_range - no
- [ ] mask_outside_range - no
- [x] clip
- [x] extract_region
- [x] extract_shape
- [x] extract_volume
- [ ] extract_trajectory - ?
- [x] extract_transect
- [x] detrend - no non-lazy version available
- [ ] multi_model_statistics - no
- [x] extract_named_regions
- [ ] depth_integration - no
- [ ] area_statistics - ? #47
- [ ] volume_statistics - no #647
- [x] amplitude
- [x] zonal_statistics
- [x] meridional_statistics
- [x] daily_statistics
- [x] monthly_statistics
- [x] seasonal_statistics
- [x] annual_statistics
- [x] decadal_statistics
- [ ] climate_statistics - not if period='full' and operator='mean' or 'sum' #336
- [ ] anomalies - not if period='full' due to use of `climate_statistics`, see above
- [x] regrid_time
- [ ] timeseries_filter - ?
- [x] cmor_check_data
- [x] convert_units

It would be great if we could make more preprocessor functions lazy. The laziness status should also be indicated in the docstrings.

**Comment by valeriupredoi** [comment]
good call!! I reckon this is a good first serious feature for v2.1 :beer:

**Comment by bouweandela** [comment]
To get an idea of the priority of the preprocessor functions, here is a rough count of which number of recipes in the ESMValTool that they are used in:
```
regrid 60
extract_region 30
derive 26
extract_levels 24
mask_landsea 21
area_statistics 20
climate_statistics 18
multi_model_statistics 16
mask_fillvalues 15
annual_statistics 8
convert_units 8
weighting_landsea_fraction 7
anomalies 7
extract_point 6
zonal_statistics 5
extract_time 4
extract_shape 4
amplitude 4
extract_season 3
detrend 3
extract_month 2
extract_transect 2
depth_integration 2
volume_statistics 2
mask_landseaice 1
extract_volume 1
extract_trajectory 1
extract_named_regions 1
meridional_statistics 1
daily_statistics 1
decadal_statistics 1
```

**Comment by Peter9192** [comment]
Two points related to this:
- It would be helpful to implement a lazy-in / lazy-out test or check for each preprocessor (we can use xfail on those that we know are not lazy yet).
- We should think about when and where to rechunk the data. Now I'm inclined to do ad-hoc rechunking whenever I need it, but this may not be the most efficient approach in the long run. See e.g. https://github.com/ESMValGroup/ESMValCore/pull/968#issuecomment-796817147

**Comment by bouweandela** [comment]
> Now I'm inclined to do ad-hoc rechunking whenever I need it

I think it makes sense to do that, because in most cases there is no need to rechunk. I would expect this is needed only for preprocessor functions that dramatically increase chunk size, and even then it might be best to try and leave that to iris.

**Comment by Peter9192** [comment]
Some things we ran into: 
- We start to see that the timing of log messages becomes confusing for lazy evaluation. 
- We should consider the interplay between the multiprocessing on tasks and the multithreading by dask. 
- Maybe we should consider setting up some global dask configuration, or a way to tune easily.

**Comment by remi-kazeroni** [comment]
The `recipe_collins13ipcc` is one of the most demanding memory recipe that we have in ESMValTool, see [log file](https://esmvaltool.dkrz.de/shared/esmvaltool/v2.5.0-test-rc6/recipe_collins13ipcc_20220311_095418/run/main_log_debug.txt) for a test run for the v2.5 release. Would it be a case that would benefit from preprocessor laziness?

**Comment by bouweandela** [comment]
Yes, it would benefit. Some progress has been made recently by @zklaus on the lazy regridding for ocean data (though I think this is currently not yet enabled by default, you need to make changes to the recipe in order to use the new functionality and install an extra package manually). Lazy vertical interpolation would be a good next candidate to tackle.
